spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/mytest?useSSL=false&useUnicode=true&characterEncoding=UTF-8
mybatis-plus:
  mapper-locations: classpath:\test\mapper\*Mapper.xml
  typeAliasesPackage: com.zxx.demorepository.test.entity

msg: "hello i am a msg!"